clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
install:
  - cinst sbt -y
  - cmd: SET PATH=%PATH;"C:\Program Files (x86)\sbt\bin"
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET JAVA_TOOL_OPTIONS=-Dfile.encoding="UTF-8"
platform:
  - x64
build_script:
  - sbt formatCheckStrict test:formatCheckStrict it:formatCheckStrict compile
  - sbt "project saulWebapp" compile
test_script:
  - sbt "test-only -- -l edu.illinois.cs.cogcomp.saulexamples.HighMemoryTest"
cache:
  - '%USERPROFILE%\.ivy2\cache -> build.sbt'
